version: '3'
services:
  db:
    image: postgres:9.6.3
    expose:
      - "5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  web:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_USER: postgres
      DATABASE_PASSWORD:
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      SECRET_KEY_BASE: "changeme"
      DEVISE_SECRET_KEY: "changemetoo"
      RAILS_LOG_TO_STDOUT:
    links:
      - db
