version: '3'
services:
  web:
    build: .
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/witchcoder
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
